### ISSUE TITLE
Important

### ISSUE THREAD

**Issue by AshutoshAJ** [shizhang124/yolov5-service-#1]
Hey shzhang124, Nice work. I just raised this issue coz I need your help.
I am building a Flask app, with YoloV5. But I'm stuck. Please respond.

**Comment by shizhang124** [comment]
this project need flask and gunicorn,  just type `pip install flask gunicorn`  in your python environment. then `./start.sh` to start the service

**Comment by AshutoshAJ** [comment]
Thanks @shizhang124  for the quick response.
But I'm building my own flask app. I need to call the detect method (detect.py) from another script (app.py).
I want to pass only an image_file_path and the detect method as usual will save the image.
I am new to python and I couldn't figure out how things work around here.

**Comment by AshutoshAJ** [comment]
Also, you have explicitly assigned the gpu usage, without which the code breaks. And people without a gpu won't be able to use your work.

**Comment by AshutoshAJ** [comment]
Just help me to modify the detect method so that it will accept a image and as usual store the predicted image in a desired location.
